# Generated by Django 4.2.30 on 2026-07-07 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_1', models.CharField(max_length=15)),
                ('phone_2', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('post_office', models.CharField(max_length=100)),
                ('tehsil', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('product_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_1_count', models.IntegerField(default=0)),
                ('product_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_2_count', models.IntegerField(default=0)),
                ('product_3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_3_count', models.IntegerField(default=0)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_repeat', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
