# Generated by Django 4.2.30 on 2026-07-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_1_count',
            new_name='total_bottles',
        ),
        migrations.RemoveField(
            model_name='order',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_1_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_2_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_2_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_3_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_3_name',
        ),
        migrations.AddField(
            model_name='order',
            name='emp',
            field=models.CharField(default='System', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='items_summary',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone1',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='tehsil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
